# Protocol constants for the virtual device.

CMD_QUERY_INFO = 0x10
CMD_UPDATE_PIXELS = 0x11
CMD_FRAGMENT_PIXELS = 0x12
CMD_FRAME_END = 0x13
CMD_QUERY_CONFIG = 0x14

PROTOCOL_VERSION = 4

MAX_UDP_PAYLOAD = 1400
